[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/books"
  to = "/.netlify/functions/books"
  status = 200

[[redirects]]
  from = "/api/books/*"
  to = "/.netlify/functions/books/:splat"
  status = 200
